/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.example.domain.Character;
import org.example.service.GameService;
import org.example.service.impl.GameServiceImpl;
import org.junit.jupiter.api.Test;

class GameTest {

    @Test
    void givenCreatedCharacter_WhenQuery_ThenReturnIt() {
        GameService gameService = new GameServiceImpl();
        String playerName = "player_1";

        Character character = gameService.createCharacter(playerName);

        assertEquals(playerName, character.getName());
        assertEquals(playerName, gameService.queryCurrentCharacter().getName());
    }
}
